name: Code Quality

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  quality:
    name: format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Erlang/Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.2"
          otp-version: "27.3.3"
          version-type: strict

      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: deps/
          key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Restore cached build artifacts
        uses: actions/cache@v4
        with:
          path: _build/dev/
          key: build-dev-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}-${{ github.sha }}
          restore-keys: |
            build-dev-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}-
            build-dev-${{ runner.os }}-

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check for unused dependencies
        run: mix deps.unlock --check-unused

      - name: Check compilation warnings
        run: mix compile --warnings-as-errors
